# Generated by Django 4.1.2 on 2022-11-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
