# Generated by Django 4.1.2 on 2022-11-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_alter_admin_options_alter_admin_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
